FORMAT: 1A
HOST: https://api.grafana.net/

# Grafana Synthetic Monitoring API

# Authentication

Synthetic Monitoring API is hosted at [synthetic-monitoring-api.grafana.net](https://synthetic-monitoring-api.grafana.net)

All the entry points that indicate that they require authentication must
provide an access token obtained by calling `/api/v1/register/install`.

The access token MUST be used in authenticated API calls in a
`Authorization` header like the following:

```
Authorization: Bearer <accessToken>
```

Source: https://github.com/grafana/synthetic-monitoring-api-go-client/blob/master/docs/API.md

## Group Checks 

#### GET /api/v1/check/list

List all the checks for the tenant associated with the authorization token.

Authorization required: yes


+ Response 200 (application/json)

        [
          <check>,
          ...
        ]

#### POST /api/v1/checks/add

+ Request (application/json; charset=utf-8)

        {
            "target": <string>,
            "job": <string>,
            "frequency": <int>,
            "timeout": <int>,
            "enabled": <boolean>,
            "probes": [
              <int>,
              ...
            ],
            "labels": [
              {
                "name": <string>,
                "value": <string>
              },
              ...
            ],
            "settings": <CheckSettings>
        }

+ Response 200 (application/json)

        {
            "id": <int>,
            "tenantId": <int>,
            "target": <string>,
            "job": <string>,
            "frequency": <int>,
            "timeout": <int>,
            "enabled": <boolean>,
            "probes": [
              <int>,
              ...
            ],
            "labels": [
              {
                "name": <string>,
                "value": <string>
              },
              ...
            ],
            "settings": <CheckSettings>,
            "created": <timestamp>,
            "modified": <timestamp>
        }

#### POST /api/v1/checks/update

+ Request (application/json; charset=utf-8)

        {
            "id": <int>,
            "tenantId": <int>,
            "target": <string>,
            "job": <string>,
            "frequency": <int>,
            "timeout": <int>,
            "enabled": <boolean>,
            "probes": [
              <int>,
              ...
            ],
            "labels": [
              {
                "name": <string>,
                "value": <string>
              },
              ...
            ],
            "settings": <CheckSettings>
        }
         
+ Response 200 (application/json)

        {
            "id": <int>,
            "tenantId": <int>,
            "target": <string>,
            "job": <string>,
            "frequency": <int>,
            "timeout": <int>,
            "enabled": <boolean>,
            "probes": [
              <int>,
              ...
            ],
            "labels": [
              {
                "name": <string>,
                "value": <string>
              },
              ...
            ],
            "settings": <CheckSettings>,
            "created": <timestamp>,
            "modified": <timestamp>
        }

#### DELETE /api/v1/check/delete/{id}

The check with the specified ID is deleted.

Authorization required: yes


+ Parameters 
    + id: 1 (number) - tenant ID

+ Response 200 (application/json)

        {
          "msg": "check deleted",
          "checkId": <int>
        }